# Generated by Django 5.0 on 2023-12-22 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_coins_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='old_price',
            field=models.IntegerField(default=10),
        ),
    ]
